# Generated by Django 6.0.3 on 2026-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icao_hex', models.CharField(max_length=200)),
                ('tail_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DropZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('field_elevation', models.FloatField()),
                ('awos_station_id', models.CharField(max_length=5)),
                ('adsb_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_set', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('heading', models.IntegerField()),
                ('active', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
