# Generated by Django 6.0.3 on 2026-03-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
