# Generated by Django 6.0.3 on 2026-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_spot_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='exit_altitude',
            field=models.IntegerField(default=12500),
            preserve_default=False,
        ),
    ]
