# Generated by Django 6.0.3 on 2026-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_spot_exit_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='notes',
            field=models.TextField(blank=True, default=12500, null=True),
        ),
    ]
