# Generated by Django 6.0.3 on 2026-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_spot_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spot',
            name='exit_altitude',
            field=models.IntegerField(default=12500),
        ),
        migrations.AlterField(
            model_name='spot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
