# Generated by Django 6.0.3 on 2026-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_spot_active_alter_spot_exit_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropzone',
            name='no_wind_heading',
            field=models.IntegerField(default=110),
            preserve_default=False,
        ),
    ]
